;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Tue Apr 4 2017
; Processor: ATmega16
; Compiler:  AVRASM (Proteus)
;====================================================================

;====================================================================
; DEFINITIONS
;====================================================================

;====================================================================
; VARIABLES
;====================================================================

;====================================================================
; RESET and INTERRUPT VECTORS
;====================================================================

      ; Reset Vector
      rjmp  Start

;====================================================================
; CODE SEGMENT
;====================================================================
.cseg
BCD_to_7_seg: .DB 0x3f, 0x06, 0x5b, 0x4f, 0x66, 0x6d, 0x7d, 0x07, 0x7f, 0x6f

delay:
      ldi r16, 0xFF
delay_loop_1:
      ldi r17, 0xFF
delay_loop_2:
      nop
      dec r17
      cpi r17, 0x00
      brne delay_loop_2
      dec r16
      cpi r16, 0x00
      brne delay_loop_1
ret

Start:
      ldi r16, 0x7f
      ldi r17, 0xff
      ldi r18, 0x03
      ldi zl, low(BCD_to_7_seg)
      ldi zh, high(BCD_to_7_seg)
      lpm R16, Z
      out DDRA, r17
      out PORTA, r16
Counting:
      call Delay
      inc r30
      lpm R16, Z
      out PORTA, r16
      cpi r30, 0x0B
      breq Loop
      rjmp Counting


      ; Write your code here

Loop:
      rjmp  Loop

;====================================================================

