;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Tue May 9 2017
; Processor: ATmega16
; Compiler:  AVRASM (Proteus)
;====================================================================

;====================================================================
; DEFINITIONS
;====================================================================
.def timer=R16
.def temp=R17
.def counter=R18
;====================================================================
; VARIABLES
;====================================================================

;====================================================================
; RESET and INTERRUPT VECTORS
;====================================================================

      ; Reset Vector

      ; Set prescalar to 1024
      ldi timer, (1 << CS02) | (0 << CS01) | (1 << CS00) | (0 << WGM00) | (0 << WGM01)
      out TCCR0, timer

      ; Initialize the timer counter
      ldi temp, 0
      out TCNT0, temp

      ; Initialize the DDRD
      sbi DDRD, DDD5
      sbi DDRD, DDD4

      cbi PORTD, PORTD5
      cbi PORTD, PORTD4

      rjmp  Start

ToggleD5:
      sbic PORTD, PORTD5
      rjmp TurnOffD5
      rjmp TurnOnD5
TurnOnD5:
      sbi PORTD, PORTD5
      ret
TurnOffD5:
      cbi PORTD, PORTD5
      ret

ToggleD4:
      sbic PORTD, PORTD4
      rjmp TurnOffD4
      rjmp TurnOnD4
TurnOnD4:
      sbi PORTD, PORTD4
      ret
TurnOffD4:
      cbi PORTD, PORTD4
      ret
;====================================================================
; CODE SEGMENT
;====================================================================

Start:
      ; Write your code here

Loop:
      in temp, TIFR
      sbrs temp, TOV0
      rjmp Loop

      cbr temp, TOV0
      inc counter
      cpi counter, 4

      brne Loop

      ldi counter, 0
      rcall ToggleD5
      rcall ToggleD4
      rjmp  Loop

;====================================================================

