;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Tue May 9 2017
; Processor: ATmega16
; Compiler:  AVRASM (Proteus)
;====================================================================

;====================================================================
; DEFINITIONS
;====================================================================
.def timer=R16
.def temp=R17
.def counter=R18
;====================================================================
; VARIABLES
;====================================================================

;====================================================================
; RESET and INTERRUPT VECTORS
;====================================================================

      ; Reset Vector
      ; Set prescalar to 1024
      ; Enable phase correct PWM
      ldi timer, (1 << CS02) | (0 << CS01) | (1 << CS00) | (1 << WGM00) | (1 << WGM01) | (1 << COM00) | (1 << COM01)
      out TCCR0, timer

      ; Initialize the timer counter
      ldi temp, 0
      out TCNT0, temp

      ; I/O Configuration

      clr temp
      ldi temp, (1 << DDB3)
      out DDRB, temp

      clr temp
      ldi temp, (1 << DDD4) | (1 << DDD5)
      out DDRD, temp
      sbi PORTD, PORTD6
      sbi PORTD, PORTD7

      rjmp  Start

;====================================================================
; CODE SEGMENT
;====================================================================
FrequencyHigh:
      ldi temp, 64
      out OCR0, temp
      ret

FrequencyLow:
      ldi temp, 4
      out OCR0, temp
      ret

CheckSW1:
      sbic PIND, 7
      call FrequencyHigh
      ret

CheckSW2:
      sbic PIND, 6
      call FrequencyLow
      ret

Start:
      ; Write your code here
Loop:
      call CheckSW1
      call CheckSW2
      jmp  Loop

;====================================================================

