;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Tue May 9 2017
; Processor: ATmega16
; Compiler:  AVRASM (Proteus)
;====================================================================

;====================================================================
; DEFINITIONS
;====================================================================
.def timer=R16
.def temp=R17
;====================================================================
; VARIABLES
;====================================================================

;====================================================================
; RESET and INTERRUPT VECTORS
;====================================================================

      ; Reset Vector

      ; Set prescalar to 1024
      ; CTC Mode
      ; Toggle OC0 on compare match
      ldi timer, (1 << CS02) | (0 << CS01) | (1 << CS00) | (0 << WGM00) | (1 << WGM01) | (0 << COM01) | (1 << COM00)
      out TCCR0, timer

      ; OCR0 initialization
      ldi temp, 0x80
      out OCR0, temp

      ; Initialize the timer counter
      ldi temp, 0
      out TCNT0, temp

      sbi DDRB, DDB3

      rjmp  Start

;====================================================================
; CODE SEGMENT
;====================================================================

Start:
      ; Write your code here

Loop:

      rjmp  Loop

;====================================================================

